spring:
  application:
    name: Math.AI
  profiles:
    include: local

  kafka-producer:
    key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
    value-serializer-class: org.apache.kafka.common.serialization.StringSerializer
    batch-size: 16384
    batch-size-boost-factor: 2
    linger-ms: 1
    compression-type: gzip
    acks: all
    request-timeout-ms: 30000
    retry-count: 3

kafka-config:
  bootstrap-servers: http://localhost:19092, http://localhost:29092
  schema-registry-url: http://localhost:8081
  schema-registry-url-key: schema.registry.url

kafka-consumer:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  attempt-analysis-consumer-group-id: attempt-analysis-topic-consumer
  like-add-consumer-group-id: like-add-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

user-service:
  like-add-request-topic-name: like-add-request

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
