/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.my.kafka.infra.avrobuild;
@org.apache.avro.specific.AvroGenerated
public enum AnalysisType implements org.apache.avro.generic.GenericEnumSymbol<AnalysisType> {
  ATTEMPT, QUESTION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AnalysisType\",\"namespace\":\"com.example.demo.my.kafka.infra.avrobuild\",\"symbols\":[\"ATTEMPT\",\"QUESTION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
