/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.my.kafka.infra.avrobuild;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EncodedImage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1657721434141153071L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EncodedImage\",\"namespace\":\"com.example.demo.my.kafka.infra.avrobuild\",\"fields\":[{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EncodedImage> ENCODER =
      new BinaryMessageEncoder<EncodedImage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EncodedImage> DECODER =
      new BinaryMessageDecoder<EncodedImage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EncodedImage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EncodedImage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EncodedImage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EncodedImage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EncodedImage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EncodedImage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EncodedImage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EncodedImage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EncodedImage() {}

  /**
   * All-args constructor.
   * @param url The new value for url
   */
  public EncodedImage(java.lang.String url) {
    this.url = url;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return url;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: url = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'url' field.
   * @return The value of the 'url' field.
   */
  public java.lang.String getUrl() {
    return url;
  }


  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.String value) {
    this.url = value;
  }

  /**
   * Creates a new EncodedImage RecordBuilder.
   * @return A new EncodedImage RecordBuilder
   */
  public static com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder newBuilder() {
    return new com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder();
  }

  /**
   * Creates a new EncodedImage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EncodedImage RecordBuilder
   */
  public static com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder newBuilder(com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder other) {
    if (other == null) {
      return new com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder();
    } else {
      return new com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder(other);
    }
  }

  /**
   * Creates a new EncodedImage RecordBuilder by copying an existing EncodedImage instance.
   * @param other The existing instance to copy.
   * @return A new EncodedImage RecordBuilder
   */
  public static com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder newBuilder(com.example.demo.my.kafka.infra.avrobuild.EncodedImage other) {
    if (other == null) {
      return new com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder();
    } else {
      return new com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder(other);
    }
  }

  /**
   * RecordBuilder for EncodedImage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EncodedImage>
    implements org.apache.avro.data.RecordBuilder<EncodedImage> {

    private java.lang.String url;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing EncodedImage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.demo.my.kafka.infra.avrobuild.EncodedImage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'url' field.
      * @return The value.
      */
    public java.lang.String getUrl() {
      return url;
    }


    /**
      * Sets the value of the 'url' field.
      * @param value The value of 'url'.
      * @return This builder.
      */
    public com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder setUrl(java.lang.String value) {
      validate(fields()[0], value);
      this.url = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'url' field has been set.
      * @return True if the 'url' field has been set, false otherwise.
      */
    public boolean hasUrl() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'url' field.
      * @return This builder.
      */
    public com.example.demo.my.kafka.infra.avrobuild.EncodedImage.Builder clearUrl() {
      url = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EncodedImage build() {
      try {
        EncodedImage record = new EncodedImage();
        record.url = fieldSetFlags()[0] ? this.url : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EncodedImage>
    WRITER$ = (org.apache.avro.io.DatumWriter<EncodedImage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EncodedImage>
    READER$ = (org.apache.avro.io.DatumReader<EncodedImage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.url);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.url = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.url = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










