/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.my.kafka.infra.avrobuild;
@org.apache.avro.specific.AvroGenerated
public enum MessageType implements org.apache.avro.generic.GenericEnumSymbol<MessageType> {
  TEXT, IMAGE_URL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageType\",\"namespace\":\"com.example.demo.my.kafka.infra.avrobuild\",\"symbols\":[\"TEXT\",\"IMAGE_URL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
